-- 8. Prix forfaitaire par m2
CREATE TABLE prix_par_m2 (
    id BIGSERIAL PRIMARY KEY,
    valeur NUMERIC(10,2) NOT NULL,
    date_modif TIMESTAMP(6) DEFAULT NOW()
);

-- 9. Niveaux de réparation
CREATE TABLE niveau_reparation (
    id BIGSERIAL PRIMARY KEY,
    valeur INT NOT NULL CHECK (valeur BETWEEN 1 AND 10),
    libelle VARCHAR(50)
);
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE roleutilisateur AS ENUM ('VISITEUR', 'UTILISATEUR', 'MANAGER');
CREATE TYPE statuttravaux AS ENUM ('NOUVEAU', 'EN_ATTENTE', 'EN_COURS', 'TERMINE', 'ANNULE');
CREATE TYPE synctype AS ENUM ('PULL', 'PUSH');

CREATE CAST (varchar AS roleutilisateur) WITH INOUT AS IMPLICIT;
CREATE CAST (roleutilisateur AS varchar) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS statuttravaux) WITH INOUT AS IMPLICIT;
CREATE CAST (statuttravaux AS varchar) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS synctype) WITH INOUT AS IMPLICIT;
CREATE CAST (synctype AS varchar) WITH INOUT AS IMPLICIT;

-- 1. Utilisateur
CREATE TABLE utilisateur (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(150) UNIQUE NOT NULL,
    mot_de_passe TEXT NOT NULL,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    role roleutilisateur NOT NULL DEFAULT 'UTILISATEUR',
    tentatives_echouees INT NOT NULL DEFAULT 0,
    est_bloque BOOLEAN DEFAULT FALSE,
    date_creation TIMESTAMP(6) DEFAULT NOW(),
    telephone VARCHAR(20)
);

CREATE TABLE parametre_systeme (
    cle VARCHAR(80) PRIMARY KEY,
    valeur VARCHAR(50) NOT NULL
);

-- 2. Entreprise
CREATE TABLE entreprise (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom VARCHAR(150) NOT NULL UNIQUE,
    contact VARCHAR(100)
);

-- 3. Signalement
CREATE TABLE signalement (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titre VARCHAR(150),
    description TEXT,
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    surface_m2 NUMERIC(10,2),
    budget NUMERIC(14,2),
    statut statuttravaux NOT NULL DEFAULT 'NOUVEAU',
    date_signalement TIMESTAMP(6) DEFAULT NOW(),
    date_en_cours TIMESTAMP(6),
    date_termine TIMESTAMP(6),
    image_urls TEXT,
    firestore_id VARCHAR(255),

    id_utilisateur UUID,
    id_entreprise UUID,

    CONSTRAINT fk_signalement_user
        FOREIGN KEY (id_utilisateur)
        REFERENCES utilisateur(id),

    CONSTRAINT fk_signalement_entreprise
        FOREIGN KEY (id_entreprise)
        REFERENCES entreprise(id)
);

CREATE TABLE historique_statut (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_signalement UUID NOT NULL,
    ancien_statut statuttravaux,
    nouveau_statut statuttravaux,
    date_modification TIMESTAMP(6) DEFAULT NOW(),
    modifie_par UUID,

    CONSTRAINT fk_hist_signalement
        FOREIGN KEY (id_signalement)
        REFERENCES signalement(id),

    CONSTRAINT fk_hist_manager
        FOREIGN KEY (modifie_par)
        REFERENCES utilisateur(id)
);

-- 4. Session utilisateur
CREATE TABLE session_utilisateur (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_utilisateur UUID NOT NULL,
    token TEXT UNIQUE NOT NULL,
    date_creation TIMESTAMP(6) DEFAULT NOW(),
    date_expiration TIMESTAMP NOT NULL,

    CONSTRAINT fk_session_user
        FOREIGN KEY (id_utilisateur)
        REFERENCES utilisateur(id)
        ON DELETE CASCADE
);

-- 5. Firebase Sync
CREATE TABLE firebase_sync (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type_donnee VARCHAR(50), 
    id_reference UUID,
    sens synctype,
    date_sync TIMESTAMP(6) DEFAULT NOW()
);

-- 6. App Config
CREATE TABLE app_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    updated_at TIMESTAMP(6)
);

-- 7. Notifications
CREATE TABLE notification (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titre VARCHAR(255) NOT NULL,
    message TEXT,
    signalement_id UUID REFERENCES signalement(id),
    date_creation TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    lu BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================================
-- INDEX
-- ============================================================

CREATE INDEX idx_signalement_statut ON signalement(statut);
CREATE INDEX idx_signalement_utilisateur ON signalement(id_utilisateur);
CREATE INDEX idx_signalement_entreprise ON signalement(id_entreprise);
CREATE INDEX idx_signalement_firestore ON signalement(firestore_id);
CREATE INDEX idx_session_token ON session_utilisateur(token);
CREATE INDEX idx_session_utilisateur ON session_utilisateur(id_utilisateur);
CREATE INDEX idx_firebase_sync_type ON firebase_sync(type_donnee);
CREATE INDEX idx_notification_date ON notification(date_creation DESC);
CREATE INDEX idx_notification_lu ON notification(lu);
