spring.application.name=web
spring.jpa.open-in-view=false

auth.mode=offline
auth.maxLoginAttempts=3
auth.lockMinutes=15
auth.jwt.secret=change-me-in-env
auth.jwt.ttlMinutes=120
auth.manager.email=manager@clouds5.local
auth.manager.password=manager123
firebase.credentials.path=

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
