-- ============================================================
-- SCRIPT COMPLET : SCHEMA + INSERTION
-- Projet Cloud S5 — PostgreSQL 15 local
-- Aligné avec les entités Java (Hibernate ddl-auto=update)
-- ============================================================

-- Nettoyage complet
DROP TABLE IF EXISTS firebase_sync CASCADE;
DROP TABLE IF EXISTS session_utilisateur CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS signalement CASCADE;
DROP TABLE IF EXISTS entreprise CASCADE;
DROP TABLE IF EXISTS app_config CASCADE;
-- DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS historique_statut CASCADE;
DROP TABLE IF EXISTS parametre_systeme CASCADE;

DROP TYPE IF EXISTS roleutilisateur CASCADE;
DROP TYPE IF EXISTS statuttravaux CASCADE;
DROP TYPE IF EXISTS synctype CASCADE;

-- ============================================================
-- TYPES ENUM
-- ============================================================

CREATE TYPE roleutilisateur AS ENUM ('VISITEUR', 'UTILISATEUR', 'MANAGER');
CREATE TYPE statuttravaux AS ENUM ('NOUVEAU', 'EN_ATTENTE', 'EN_COURS', 'TERMINE', 'ANNULE');
CREATE TYPE synctype AS ENUM ('PULL', 'PUSH');

-- Casts implicites pour Hibernate
CREATE CAST (varchar AS roleutilisateur) WITH INOUT AS IMPLICIT;
CREATE CAST (roleutilisateur AS varchar) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS statuttravaux) WITH INOUT AS IMPLICIT;
CREATE CAST (statuttravaux AS varchar) WITH INOUT AS IMPLICIT;
CREATE CAST (varchar AS synctype) WITH INOUT AS IMPLICIT;
CREATE CAST (synctype AS varchar) WITH INOUT AS IMPLICIT;

-- ============================================================
-- TABLES
-- ============================================================

-- 1. Utilisateur
CREATE TABLE utilisateur (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email               VARCHAR(150) NOT NULL UNIQUE,
    mot_de_passe        TEXT NOT NULL,
    nom                 VARCHAR(100),
    prenom              VARCHAR(100),
    role                roleutilisateur NOT NULL DEFAULT 'UTILISATEUR',
    tentatives_echouees INTEGER NOT NULL DEFAULT 0,
    est_bloque          BOOLEAN DEFAULT FALSE,
    date_creation       TIMESTAMP(6) DEFAULT NOW(),
    telephone           VARCHAR(20)
);

-- 2. Entreprise
CREATE TABLE entreprise (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nom                 VARCHAR(150) NOT NULL UNIQUE,
    contact             VARCHAR(100)
);

-- 3. Signalement
CREATE TABLE signalement (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titre               VARCHAR(150),
    description         TEXT,
    latitude            NUMERIC(9,6) NOT NULL,
    longitude           NUMERIC(9,6) NOT NULL,
    surface_m2          NUMERIC(10,2),
    budget              NUMERIC(14,2),
    statut              statuttravaux NOT NULL DEFAULT 'NOUVEAU',
    date_signalement    TIMESTAMP(6) DEFAULT NOW(),
    date_en_cours       TIMESTAMP(6),
    date_termine        TIMESTAMP(6),
    image_urls          TEXT,
    firestore_id        VARCHAR(255),
    id_utilisateur      UUID REFERENCES utilisateur(id),
    id_entreprise       UUID REFERENCES entreprise(id)
);

-- 4. Session utilisateur
CREATE TABLE session_utilisateur (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_utilisateur      UUID NOT NULL REFERENCES utilisateur(id),
    token               TEXT NOT NULL UNIQUE,
    date_creation       TIMESTAMP(6) DEFAULT NOW(),
    date_expiration     TIMESTAMP(6) NOT NULL
);

-- 5. Firebase Sync
CREATE TABLE firebase_sync (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type_donnee         VARCHAR(50),
    id_reference        UUID,
    type_sync           synctype,
    date_sync           TIMESTAMP(6) DEFAULT NOW()
);

-- 6. App Config
CREATE TABLE app_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key          VARCHAR(255) NOT NULL UNIQUE,
    config_value        VARCHAR(255) NOT NULL,
    description         VARCHAR(255),
    updated_at          TIMESTAMP(6)
);

-- 7. Notifications
CREATE TABLE notification (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titre               VARCHAR(255) NOT NULL,
    message             TEXT,
    signalement_id      UUID REFERENCES signalement(id),
    date_creation       TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    lu                  BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================================
-- INDEX
-- ============================================================

CREATE INDEX idx_signalement_statut ON signalement(statut);
CREATE INDEX idx_signalement_utilisateur ON signalement(id_utilisateur);
CREATE INDEX idx_signalement_entreprise ON signalement(id_entreprise);
CREATE INDEX idx_signalement_firestore ON signalement(firestore_id);
CREATE INDEX idx_session_token ON session_utilisateur(token);
CREATE INDEX idx_session_utilisateur ON session_utilisateur(id_utilisateur);
CREATE INDEX idx_firebase_sync_type ON firebase_sync(type_donnee);
CREATE INDEX idx_notification_date ON notification(date_creation DESC);
CREATE INDEX idx_notification_lu ON notification(lu);

-- ============================================================
-- VUES
-- ============================================================

CREATE OR REPLACE VIEW v_carte_signalements AS
SELECT
    s.id,
    s.latitude,
    s.longitude,
    s.surface_m2,
    s.budget,
    s.statut,
    s.date_signalement,
    s.image_urls,
    e.nom AS entreprise_nom
FROM signalement s
LEFT JOIN entreprise e ON s.id_entreprise = e.id;

CREATE OR REPLACE VIEW v_recap_global AS
SELECT
    COUNT(*) AS nombre_points,
    COALESCE(SUM(s.surface_m2), 0) AS surface_totale,
    COALESCE(SUM(s.budget), 0) AS budget_total,
    ROUND(AVG(
        CASE s.statut
            WHEN 'NOUVEAU' THEN 0
            WHEN 'EN_COURS' THEN 50
            WHEN 'TERMINE' THEN 100
            ELSE 0
        END
    ), 1) AS avancement_pct
FROM signalement s;

-- ============================================================
-- INSERTIONS
-- ============================================================

-- Manager par défaut : créé automatiquement par BootstrapManagerConfig au démarrage
-- avec le bon hash BCrypt de "manager123". Ne PAS insérer manuellement ici.

-- Entreprises
INSERT INTO entreprise (id, nom, contact) VALUES
    (gen_random_uuid(), 'Colas Madagascar', 'contact@colas.mg'),
    (gen_random_uuid(), 'SOGEA SATOM', 'info@sogea-satom.mg'),
    (gen_random_uuid(), 'Entreprise REDO', 'contact@redo.mg');

-- Configuration application
INSERT INTO app_config (config_key, config_value, description, updated_at) VALUES
    ('session.duration.minutes', '30', 'Durée de session en minutes', NOW()),
    ('auth.max.login.attempts', '3', 'Nombre maximum de tentatives de connexion', NOW());

-- ============================================================
-- DONNÉES DE TEST (signalements à Antananarivo)
-- ============================================================

INSERT INTO signalement (id, titre, description, latitude, longitude, surface_m2, budget, statut, date_signalement)
VALUES
    (gen_random_uuid(), 'Nid-de-poule Analakely', 'Route principale endommagée', -18.9100, 47.5255, 15.5, 2500000, 'NOUVEAU', NOW()),
    (gen_random_uuid(), 'Fissure route Ambodivona', 'Fissures profondes sur la chaussée', -18.9050, 47.5300, 25.0, 4000000, 'EN_COURS', NOW()),
    (gen_random_uuid(), 'Trou Isotry', 'Gros trou dangereux', -18.9130, 47.5190, 8.0, 1200000, 'NOUVEAU', NOW()),
    (gen_random_uuid(), 'Dégradation Anosy', 'Revêtement dégradé près du lac', -18.9200, 47.5280, 30.0, 5500000, 'TERMINE', NOW()),
    (gen_random_uuid(), 'Affaissement Tsaralalana', 'Affaissement de la route', -18.9080, 47.5230, 12.0, 3000000, 'EN_COURS', NOW());
